server:
  port: 8888
spring:
  application:
    name: Gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              -GET
              -POST
              -PUT
              -Delete